from pathlib import Path
p=Path('server.js')
s=p.read_text()
old="""app.patch('/api/admin/verifications/:id', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const status = String(req.body.status || '');\n    if (!['verified','rejected'].includes(status)) return res.status(400).json({ error: 'Estado de verificación inválido' });\n    const { rows } = await pool.query(`UPDATE users SET identity_status=$1 WHERE id=$2 AND role='user'\n      RETURNING id,name,email,identity_status AS \"identityStatus\"`, [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Usuario no encontrado' });\n    res.json(rows[0]);\n  } catch (e) { next(e); }\n});\n"""
new="""app.patch('/api/admin/verifications/:id', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const status = String(req.body.status || '');\n    if (!['verified','rejected'].includes(status)) return res.status(400).json({ error: 'Estado de verificación inválido' });\n    const { rows } = await pool.query(`UPDATE users SET identity_status=$1 WHERE id=$2 AND role='user'\n      RETURNING id,name,email,identity_status AS \"identityStatus\"`, [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Usuario no encontrado' });\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,$2,'user',$3,$4)`,\n      [req.user.id, status === 'verified' ? 'verification_approved' : 'verification_rejected', req.params.id, status === 'verified' ? 'Verificación aprobada' : 'Verificación rechazada']);\n    res.json(rows[0]);\n  } catch (e) { next(e); }\n});\n"""
if old not in s: raise SystemExit('verification block not found')
s=s.replace(old,new,1)
old="""app.get('/api/admin/services', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const q = String(req.query.q || '').trim().slice(0,100);\n    const pattern = `%${q}%`;\n    const { rows } = await pool.query(`SELECT s.id,s.name,s.category,s.area,s.active,s.created_at AS \"createdAt\",\n      u.id AS \"providerId\",u.name AS \"providerName\",u.email AS \"providerEmail\",\n      (SELECT COUNT(*)::int FROM bookings b WHERE b.service_id=s.id) AS \"bookingCount\"\n      FROM services s JOIN users u ON u.id=s.provider_id\n      WHERE ($1='' OR s.name ILIKE $2 OR u.name ILIKE $2 OR u.email ILIKE $2)\n      ORDER BY s.created_at DESC LIMIT 300`, [q, pattern]);\n    res.json(rows);\n  } catch (e) { next(e); }\n});\n"""
new="""app.get('/api/admin/services', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const q = String(req.query.q || '').trim().slice(0,100);\n    const state = String(req.query.state || 'all');\n    if (!['all','active','removed'].includes(state)) return res.status(400).json({ error: 'Filtro de servicio inválido' });\n    const pattern = `%${q}%`;\n    const { rows } = await pool.query(`SELECT s.id,s.name,s.category,s.area,s.active,s.created_at AS \"createdAt\",\n      u.id AS \"providerId\",u.name AS \"providerName\",u.email AS \"providerEmail\",\n      (SELECT COUNT(*)::int FROM bookings b WHERE b.service_id=s.id) AS \"bookingCount\"\n      FROM services s JOIN users u ON u.id=s.provider_id\n      WHERE ($1='' OR s.name ILIKE $2 OR u.name ILIKE $2 OR u.email ILIKE $2)\n        AND ($3='all' OR ($3='active' AND s.active=TRUE) OR ($3='removed' AND s.active=FALSE))\n      ORDER BY s.created_at DESC LIMIT 300`, [q, pattern, state]);\n    res.json(rows);\n  } catch (e) { next(e); }\n});\n"""
if old not in s: raise SystemExit('services block not found')
s=s.replace(old,new,1)
marker="app.get('/api/admin/users/:id/details', auth, allow('admin'), async (req, res, next) => {"
activity="""app.get('/api/admin/activity', auth, allow('admin'), async (_req, res, next) => {\n  try {\n    const { rows } = await pool.query(`SELECT a.id,a.action,a.target_type AS \"targetType\",a.target_id AS \"targetId\",a.reason,a.created_at AS \"createdAt\",\n      u.name AS \"adminName\" FROM admin_actions a JOIN users u ON u.id=a.admin_id ORDER BY a.created_at DESC LIMIT 50`);\n    res.json(rows);\n  } catch (e) { next(e); }\n});\n\n"""
if marker not in s: raise SystemExit('details marker not found')
s=s.replace(marker,activity+marker,1)
old="""app.get('/api/admin/users', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const q = String(req.query.q || '').trim().slice(0,100);\n    const pattern = `%${q}%`;\n    const { rows } = await pool.query(`SELECT u.id,u.name,u.email,u.role,u.account_status AS \"accountStatus\",\n      u.identity_status AS \"identityStatus\",u.created_at AS \"createdAt\",\n      (SELECT COUNT(*)::int FROM services s WHERE s.provider_id=u.id) AS \"serviceCount\"\n      FROM users u WHERE ($1='' OR u.name ILIKE $2 OR u.email ILIKE $2)\n      ORDER BY u.created_at DESC LIMIT 200`, [q, pattern]);\n    res.json(rows);\n  } catch (e) { next(e); }\n});\n"""
new="""app.get('/api/admin/users', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const q = String(req.query.q || '').trim().slice(0,100);\n    const account = String(req.query.account || 'all');\n    const verification = String(req.query.verification || 'all');\n    if (!['all','active','suspended'].includes(account) || !['all','verified','pending','unverified','rejected'].includes(verification))\n      return res.status(400).json({ error: 'Filtro de usuario inválido' });\n    const pattern = `%${q}%`;\n    const { rows } = await pool.query(`SELECT u.id,u.name,u.email,u.role,u.account_status AS \"accountStatus\",\n      u.identity_status AS \"identityStatus\",u.created_at AS \"createdAt\",\n      (SELECT COUNT(*)::int FROM services s WHERE s.provider_id=u.id) AS \"serviceCount\"\n      FROM users u WHERE ($1='' OR u.name ILIKE $2 OR u.email ILIKE $2)\n        AND ($3='all' OR u.account_status=$3) AND ($4='all' OR u.identity_status=$4)\n      ORDER BY u.created_at DESC LIMIT 200`, [q, pattern, account, verification]);\n    res.json(rows);\n  } catch (e) { next(e); }\n});\n"""
if old not in s: raise SystemExit('users list block not found')
s=s.replace(old,new,1)
old="""app.patch('/api/admin/users/:id/status', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const status = String(req.body.status || '');\n    if (!['active','suspended'].includes(status)) return res.status(400).json({ error: 'Estado de cuenta inválido' });\n    if (String(req.params.id) === String(req.user.id)) return res.status(400).json({ error: 'No puedes suspender tu propia cuenta admin' });\n    const { rows } = await pool.query(`UPDATE users SET account_status=$1 WHERE id=$2 AND role='user'\n      RETURNING id,name,email,account_status AS \"accountStatus\"`, [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Usuario no encontrado' });\n    res.json(rows[0]);\n  } catch (e) { next(e); }\n});\n"""
new="""app.patch('/api/admin/users/:id/status', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const status = String(req.body.status || '');\n    const reason = String(req.body.reason || '').trim().slice(0,200);\n    if (!['active','suspended'].includes(status)) return res.status(400).json({ error: 'Estado de cuenta inválido' });\n    if (status === 'suspended' && reason.length < 3) return res.status(400).json({ error: 'Debes indicar un motivo para suspender la cuenta' });\n    if (String(req.params.id) === String(req.user.id)) return res.status(400).json({ error: 'No puedes suspender tu propia cuenta admin' });\n    const { rows } = await pool.query(`UPDATE users SET account_status=$1 WHERE id=$2 AND role='user'\n      RETURNING id,name,email,account_status AS \"accountStatus\"`, [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Usuario no encontrado' });\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,$2,'user',$3,$4)`,\n      [req.user.id, status === 'suspended' ? 'user_suspended' : 'user_reactivated', req.params.id, reason || 'Cuenta reactivada por administrador']);\n    res.json(rows[0]);\n  } catch (e) { next(e); }\n});\n"""
if old not in s: raise SystemExit('user status block not found')
s=s.replace(old,new,1)
p.write_text(s)
