from pathlib import Path

path = Path('server.js')
text = path.read_text(encoding='utf-8')

old_db = '''    CREATE TABLE IF NOT EXISTS messages (\n      id BIGSERIAL PRIMARY KEY,\n      service_id BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,\n      sender_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n      recipient_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n      body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 1000),\n      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    );\n'''
new_db = old_db + '''    CREATE TABLE IF NOT EXISTS admin_actions (\n      id BIGSERIAL PRIMARY KEY,\n      admin_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n      action TEXT NOT NULL,\n      target_type TEXT NOT NULL,\n      target_id BIGINT NOT NULL,\n      reason TEXT NOT NULL DEFAULT '',\n      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()\n    );\n'''
if old_db not in text:
    raise SystemExit('messages table block not found')
text = text.replace(old_db, new_db, 1)

old_delete = '''app.delete('/api/admin/services/:id', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const { rows } = await pool.query(`UPDATE services SET active=FALSE WHERE id=$1 AND active=TRUE\n      RETURNING id,name,provider_id AS "providerId",active`, [req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Servicio no encontrado o ya eliminado' });\n    await pool.query('UPDATE availability SET available=FALSE WHERE service_id=$1 AND available=TRUE', [req.params.id]);\n    res.json({ ...rows[0], removed: true });\n  } catch (e) { next(e); }\n});\n'''
new_delete = '''app.delete('/api/admin/services/:id', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const reason = String(req.body.reason || '').trim().slice(0,200);\n    if (reason.length < 3) return res.status(400).json({ error: 'Debes indicar un motivo para retirar el servicio' });\n    const { rows } = await pool.query(`UPDATE services SET active=FALSE WHERE id=$1 AND active=TRUE\n      RETURNING id,name,provider_id AS "providerId",active`, [req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Servicio no encontrado o ya eliminado' });\n    await pool.query('UPDATE availability SET available=FALSE WHERE service_id=$1 AND available=TRUE', [req.params.id]);\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,'service_removed','service',$2,$3)`, [req.user.id, req.params.id, reason]);\n    res.json({ ...rows[0], removed: true, reason });\n  } catch (e) { next(e); }\n});\n\napp.patch('/api/admin/services/:id/restore', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const reason = String(req.body.reason || 'Restaurado por administrador').trim().slice(0,200);\n    const { rows } = await pool.query(`UPDATE services SET active=TRUE WHERE id=$1 AND active=FALSE\n      RETURNING id,name,provider_id AS "providerId",active`, [req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Servicio no encontrado o ya está activo' });\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,'service_restored','service',$2,$3)`, [req.user.id, req.params.id, reason]);\n    res.json({ ...rows[0], restored: true });\n  } catch (e) { next(e); }\n});\n'''
if old_delete not in text:
    raise SystemExit('service delete block not found')
text = text.replace(old_delete, new_delete, 1)

marker = "app.get('/api/admin/users', auth, allow('admin'), async (req, res, next) => {"
if marker not in text:
    raise SystemExit('admin users marker not found')
user_detail = '''app.get('/api/admin/users/:id/details', auth, allow('admin'), async (req, res, next) => {\n  try {\n    const { rows: users } = await pool.query(`SELECT id,name,email,role,account_status AS "accountStatus",identity_status AS "identityStatus",\n      email_verified AS "emailVerified",phone_verified AS "phoneVerified",headline,bio,skills,languages,location,experience,portfolio_url AS "portfolioUrl",created_at AS "createdAt"\n      FROM users WHERE id=$1`, [req.params.id]);\n    if (!users[0]) return res.status(404).json({ error: 'Usuario no encontrado' });\n    const { rows: services } = await pool.query(`SELECT id,name,category,active,created_at AS "createdAt",\n      (SELECT COUNT(*)::int FROM bookings b WHERE b.service_id=services.id) AS "bookingCount"\n      FROM services WHERE provider_id=$1 ORDER BY created_at DESC LIMIT 100`, [req.params.id]);\n    const { rows: bookings } = await pool.query(`SELECT b.id,b.status,b.scheduled_at AS "scheduledAt",s.name AS "serviceName",\n      CASE WHEN b.client_id=$1 THEN 'client' ELSE 'provider' END AS perspective\n      FROM bookings b JOIN services s ON s.id=b.service_id\n      WHERE b.client_id=$1 OR s.provider_id=$1 ORDER BY b.created_at DESC LIMIT 30`, [req.params.id]);\n    const { rows: reports } = await pool.query(`SELECT id,reason,status,created_at AS "createdAt" FROM reports WHERE target_user_id=$1 ORDER BY created_at DESC LIMIT 30`, [req.params.id]);\n    res.json({ user: users[0], services, bookings, reports });\n  } catch (e) { next(e); }\n});\n\n'''
text = text.replace(marker, user_detail + marker, 1)

path.write_text(text, encoding='utf-8')
