from pathlib import Path
p=Path('server.js')
s=p.read_text(encoding='utf-8')
old="""    const { rows: reports } = await pool.query(`SELECT r.id,'report' AS type,r.reason,r.details,r.status,r.created_at AS \"createdAt\",\n      reporter.name AS \"openedByName\",target.name AS \"targetName\",s.name AS \"serviceName\"\n      FROM reports r JOIN users reporter ON reporter.id=r.reporter_id\n      LEFT JOIN users target ON target.id=r.target_user_id LEFT JOIN services s ON s.id=r.service_id\n      ORDER BY r.created_at DESC LIMIT 200`);\n    const { rows: disputes } = await pool.query(`SELECT d.id,'dispute' AS type,d.booking_id AS \"bookingId\",d.reason,d.details,d.status,d.created_at AS \"createdAt\",\n      u.name AS \"openedByName\" FROM disputes d JOIN users u ON u.id=d.opened_by\n      ORDER BY d.created_at DESC LIMIT 200`);\n"""
new="""    const { rows: reports } = await pool.query(`SELECT r.id,'report' AS type,r.reason,r.details,r.status,r.created_at AS \"createdAt\",\n      r.reporter_id AS \"openedById\",r.target_user_id AS \"targetUserId\",r.service_id AS \"serviceId\",\n      reporter.name AS \"openedByName\",target.name AS \"targetName\",s.name AS \"serviceName\"\n      FROM reports r JOIN users reporter ON reporter.id=r.reporter_id\n      LEFT JOIN users target ON target.id=r.target_user_id LEFT JOIN services s ON s.id=r.service_id\n      ORDER BY r.created_at DESC LIMIT 200`);\n    const { rows: disputes } = await pool.query(`SELECT d.id,'dispute' AS type,d.booking_id AS \"bookingId\",d.reason,d.details,d.status,d.created_at AS \"createdAt\",\n      d.opened_by AS \"openedById\",u.name AS \"openedByName\",b.client_id AS \"clientId\",client.name AS \"clientName\",\n      s.provider_id AS \"providerId\",provider.name AS \"providerName\",s.id AS \"serviceId\",s.name AS \"serviceName\"\n      FROM disputes d JOIN users u ON u.id=d.opened_by JOIN bookings b ON b.id=d.booking_id\n      JOIN services s ON s.id=b.service_id JOIN users client ON client.id=b.client_id JOIN users provider ON provider.id=s.provider_id\n      ORDER BY d.created_at DESC LIMIT 200`);\n"""
if old not in s: raise SystemExit('cases block not found')
s=s.replace(old,new,1)
old2="""    const { rows } = await pool.query('UPDATE reports SET status=$1 WHERE id=$2 RETURNING id,status', [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Reporte no encontrado' });\n    res.json(rows[0]);\n"""
new2="""    const { rows } = await pool.query('UPDATE reports SET status=$1 WHERE id=$2 RETURNING id,status', [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Reporte no encontrado' });\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,$2,'report',$3,$4)`,\n      [req.user.id, 'report_'+status, req.params.id, 'Estado del reporte cambiado a '+status]);\n    res.json(rows[0]);\n"""
if old2 not in s: raise SystemExit('report status block not found')
s=s.replace(old2,new2,1)
old3="""    const { rows } = await pool.query('UPDATE disputes SET status=$1 WHERE id=$2 RETURNING id,status', [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Disputa no encontrada' });\n    res.json(rows[0]);\n"""
new3="""    const { rows } = await pool.query('UPDATE disputes SET status=$1 WHERE id=$2 RETURNING id,status', [status, req.params.id]);\n    if (!rows[0]) return res.status(404).json({ error: 'Disputa no encontrada' });\n    await pool.query(`INSERT INTO admin_actions(admin_id,action,target_type,target_id,reason) VALUES($1,$2,'dispute',$3,$4)`,\n      [req.user.id, 'dispute_'+status, req.params.id, 'Estado de la disputa cambiado a '+status]);\n    res.json(rows[0]);\n"""
if old3 not in s: raise SystemExit('dispute status block not found')
s=s.replace(old3,new3,1)
p.write_text(s,encoding='utf-8')
